//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly-typed accessors for Resources/AppResources.resx.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MindSilence.Resources;

using System.Globalization;
using System.Resources;

public static class AppResources
{
	private static ResourceManager? resourceManager;

	public static ResourceManager ResourceManager =>
		resourceManager ??= new ResourceManager("MindSilence.Resources.AppResources", typeof(AppResources).Assembly);

	public static CultureInfo? Culture { get; set; }

	public static string app_name => Get("app_name");
	public static string level_label => Get("level_label");
	public static string start => Get("start");
	public static string thought => Get("thought");
	public static string level_progress => Get("level_progress");
	public static string level_idle => Get("level_idle");
	public static string start_content_description => Get("start_content_description");
	public static string thought_content_description => Get("thought_content_description");
	public static string session_summary_title => Get("session_summary_title");
	public static string session_level_reached => Get("session_level_reached");
	public static string session_best_today => Get("session_best_today");
	public static string session_attempt_duration => Get("session_attempt_duration");
	public static string ok => Get("ok");
	public static string highscore => Get("highscore");
	public static string high_scores_title => Get("high_scores_title");
	public static string back => Get("back");
	public static string high_scores_empty => Get("high_scores_empty");
	public static string daily_attempts => Get("daily_attempts");
	public static string daily_total_time => Get("daily_total_time");
	public static string daily_best_level => Get("daily_best_level");
	public static string menu_training => Get("menu_training");
	public static string menu_how_to_train_cd => Get("menu_how_to_train_cd");
	public static string how_to_train_title => Get("how_to_train_title");
	public static string how_to_train_body => Get("how_to_train_body");

	private static string Get(string name) =>
		ResourceManager.GetString(name, Culture) ?? name;
}
